name: PR build

on: push

env:
  GIT_CONFIG_PARAMETERS: "'checkout.workers=56'"

jobs:
  sdk-artifacts:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        artifact: ['build-installers']
        bitness: ['32']
        exclude:
          - artifact: minimal
            bitness: 32
          - artifact: makepkg-git
            bitness: 32
    steps:
      - uses: actions/checkout@v3
      - name: initialize bare SDK clone
        shell: bash
        run: |
          case "${{ matrix.artifact }}" in
          full) partial=;;
          *) partial=--filter=blob:none;;
          esac &&
          git clone --bare --depth=1 --single-branch --branch=main $partial \
            https://github.com/git-for-windows/git-sdk-${{ matrix.bitness }} .sdk
      - name: build ${{ matrix.artifact }} artifact
        id: build-artifact
        shell: bash
        run: |
          case "${{ matrix.artifact }}" in
          full)
            git --git-dir=.sdk worktree add --detach sdk-artifact
            ;;
          *)
            ./please.sh create-sdk-artifact \
              --bitness=${{ matrix.bitness }} \
              --sdk=.sdk \
              --out=sdk-artifact \
              ${{ matrix.artifact }}
            ;;
          esac &&
          echo "git-version=$(sdk-artifact/cmd/git.exe version)" >>$GITHUB_OUTPUT &&
          cygpath -aw "$PWD/sdk-artifact/usr/bin/core_perl" >>$GITHUB_PATH &&
          cygpath -aw "$PWD/sdk-artifact/usr/bin" >>$GITHUB_PATH &&
          cygpath -aw "$PWD/sdk-artifact/mingw${{ matrix.bitness }}/bin" >>$GITHUB_PATH &&
          echo "MSYSTEM=MINGW${{ matrix.bitness }}" >>$GITHUB_ENV
      - name: debug with tmate
        shell: bash
        run: |
          # install tmate
          pacman -Sy --noconfirm tmate openssh &&

          # restrict SSH access via public key authentication
          # this requires calling `ssh -i <private-key> [...]` later on
          mkdir -p ~/.ssh &&
          echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSXs87cLXHuXPXjPTyb3HTDizuD07CytsUgjXazbkfzD7/EZF5g6cRWnc+gbqApQCzGSbLXxCd+AV/UxyS62v34kO/k5olz6DF6aMURbvFqrB9v0px86T0ScYjehUf5NYzGixIIghW3Pdxqi6s8BRuNuUjTGsNDzlMLA8N9pK1TOBZglsRlBUdtg7zeXBN/gkS7tf44eAw7gxMNfhrb1ackEveeu7PDUEvkoHSfMFITBgd8z4PonoxZjWrijoQXxXKuD1GtWrvfev1yc6hGnLlRK8HCnnq87eYUd5iUVO2yWNBhVkySJMp66UuHKne7uROXslIhUT98cgDU04T/ZpZ2qwQqpsl0ohDC8rqiLSeAFNZQZdjwVAXtH+FIQLT8fyHaU8HsHD4exMPUHSaKIRL0kBbPS8Wxj1qh/F3lNPPtIxEmlbpVN56xSUkFGqBJRET4FIH+UpDiQE7nsaD4rl3iys7Aj0B2gFMttOOvq8J/dFOMqX+NEyiMAHVsFT0SBnKZfk5J96kWOANbJa753QC/01G8wiMKTU6M87Ziv3mB/FqIu97+78TYhEzdAOr3V7NZp/ccx6LoD7zvcDkKCaWD9PxPX2hcv70fZ/WsZ6wrkVEmBHs3vJ7lM+caTR8ndjt9wC5ceRfI1s55wZ8AZ9PJ2PVxpm9ZYDsgsiQXIwAFQ==' >~/.ssh/authorized_keys &&
          # Generate an SSH key (needed for tmate)
          echo -e 'y\n' | ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa &&

          # Start tmate session
          export CHERE_INVOKING=1 &&
          tmate -S /tmp/tmate.sock -a ~/.ssh/authorized_keys new-session -d &&
          tmate -S /tmp/tmate.sock wait tmate-ready &&

          # Print SSH invocation
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
      - name: build installer
        if: matrix.artifact == 'build-installers'
        shell: bash
        run: ./installer/release.sh --output=$PWD/installer-${{ matrix.bitness }} 0-test
      - uses: actions/upload-artifact@v3
        if: matrix.artifact == 'build-installers'
        with:
          name: installer-${{ matrix.bitness }}
          path: installer-${{ matrix.bitness }}
      - name: run the installer
        if: matrix.artifact == 'build-installers'
        shell: pwsh
        run: |
          $exePath = Get-ChildItem -Path installer-${{ matrix.bitness }}/*.exe | %{$_.FullName}
          $installer = Start-Process -PassThru -Wait -FilePath "$exePath" -ArgumentList "/SILENT /VERYSILENT /NORESTART /SUPPRESSMSGBOXES /ALLOWDOWNGRADE=1 /ALLOWINSTALLING32ON64=1 /LOG=installer.log"
          $exitCode = $installer.ExitCode
          if ($exitCode -ne 0) {
            Write-Host "::error::Installer failed with exit code $exitCode!"
            exit 1
          }
          if ("${{ matrix.bitness }}" -eq 32) {
            "${env:ProgramFiles(x86)}\Git\usr\bin" | Out-File -Encoding ascii -Append $env:GITHUB_PATH
            "${env:ProgramFiles(x86)}\Git\mingw32\bin" | Out-File -Encoding ascii -Append $env:GITHUB_PATH
          } else {
            "$env:ProgramFiles\Git\usr\bin" | Out-File -Encoding ascii -Append $env:GITHUB_PATH
            "$env:ProgramFiles\Git\mingw32\bin" | Out-File -Encoding ascii -Append $env:GITHUB_PATH
          }
      - name: validate
        if: matrix.artifact == 'build-installers'
        shell: bash
        run: |
          echo '::group::installer.log'
          cat installer.log
          echo '::endgroup'

          set -x &&
          grep 'Installation process succeeded' installer.log &&
          ! grep -iw failed installer.log &&
          cygpath -aw / &&
          git.exe version --build-options >version &&
          cat version &&
          grep "${{ steps.build-artifact.outputs.git-version }}" version &&
          checklist=installer/run-checklist.sh &&
          # cannot test SSH keys in read-only mode, skip test for now
          sed -i 's|git@ssh.dev.azure.com:v3/git-for-windows/git/git|https://github.com/git/git|' $checklist &&
          sh -x $checklist
      - name: wait for tmate to be done
        if: always()
        shell: pwsh
        run: |
          $env:MSYSTEM = "MINGW32"
          & sdk-artifact\usr\bin\bash.exe -lc @"
            while test -e /tmp/tmate.sock
            do
              msg=\"$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')\"
              echo \"$msg\"
              case \"$msg\" in \"no server running\") exit 0;; esac
              sleep 5
            done
          "@
